Repository six-sense/1_mrCamel_team1, pull requests merged in 2021-07, with the labels that each got.

#2 Refactor: Add .vscode
  .gitignore
Labels: enhancement

#3 Feat: Install styled-components
  package-lock.json
  package.json
Labels: documentation

#12 Feat: Add webpack absolute path
  config-overrides.js
  package-lock.json
  package.json
Labels: done

#39 FEAT: #33 load product detail and make random and dislike button
  package-lock.json
  src/pages/ProductDetailPage.js
  src/utils/constants.js
  src/utils/getInterestList.js
  src/utils/getOriginalData.js
Labels: done

#54 refactor: #53 ProductDetailPage directory setting
  src/pages/ProductDetailPage/ProductDetailPage.js
  src/pages/ProductDetailPage/ProductDetailPageStyle.js
  src/pages/ProductDetailPage/index.js
Labels: done

#60 Style: #8 Title and Button
  src/pages/ProductDetailPage/ProductDetailPage.js
  src/pages/ProductDetailPage/ProductDetailPageStyle.js
Labels: doing
